spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/admin-service
    username: admin-service
    password: Password!23
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_nationalized_character_data: true